//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 06:52:30 AM WAT 
//


package asycuda;

import asycuda.Awmds;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Awmds }
     * 
     */
    public Awmds createAwmds() {
        return new Awmds();
    }
    
    /**
     * Create an instance of {@link Awmds.BolSegment }
     * 
     */
    public Awmds.BolSegment createAwmdsBolSegment() {
        return new Awmds.BolSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.ValueSegment }
     * 
     */
    public Awmds.BolSegment.ValueSegment createAwmdsBolSegmentValueSegment() {
        return new Awmds.BolSegment.ValueSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.SplitSegment }
     * 
     */
    public Awmds.BolSegment.SplitSegment createAwmdsBolSegmentSplitSegment() {
        return new Awmds.BolSegment.SplitSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.GoodsSegment }
     * 
     */
    public Awmds.BolSegment.GoodsSegment createAwmdsBolSegmentGoodsSegment() {
        return new Awmds.BolSegment.GoodsSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.TradersSegment }
     * 
     */
    public Awmds.BolSegment.TradersSegment createAwmdsBolSegmentTradersSegment() {
        return new Awmds.BolSegment.TradersSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.BolId }
     * 
     */
    public Awmds.BolSegment.BolId createAwmdsBolSegmentBolId() {
        return new Awmds.BolSegment.BolId();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment }
     * 
     */
    public Awmds.GeneralSegment createAwmdsGeneralSegment() {
        return new Awmds.GeneralSegment();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.TransportInformation }
     * 
     */
    public Awmds.GeneralSegment.TransportInformation createAwmdsGeneralSegmentTransportInformation() {
        return new Awmds.GeneralSegment.TransportInformation();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.LoadUnloadPlace }
     * 
     */
    public Awmds.BolSegment.LoadUnloadPlace createAwmdsBolSegmentLoadUnloadPlace() {
        return new Awmds.BolSegment.LoadUnloadPlace();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.CtnSegment }
     * 
     */
    public Awmds.BolSegment.CtnSegment createAwmdsBolSegmentCtnSegment() {
        return new Awmds.BolSegment.CtnSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.Location }
     * 
     */
    public Awmds.BolSegment.Location createAwmdsBolSegmentLocation() {
        return new Awmds.BolSegment.Location();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.ValueSegment.FreightSegment }
     * 
     */
    public Awmds.BolSegment.ValueSegment.FreightSegment createAwmdsBolSegmentValueSegmentFreightSegment() {
        return new Awmds.BolSegment.ValueSegment.FreightSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.ValueSegment.CustomsSegment }
     * 
     */
    public Awmds.BolSegment.ValueSegment.CustomsSegment createAwmdsBolSegmentValueSegmentCustomsSegment() {
        return new Awmds.BolSegment.ValueSegment.CustomsSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.ValueSegment.InsuranceSegment }
     * 
     */
    public Awmds.BolSegment.ValueSegment.InsuranceSegment createAwmdsBolSegmentValueSegmentInsuranceSegment() {
        return new Awmds.BolSegment.ValueSegment.InsuranceSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.ValueSegment.TransportSegment }
     * 
     */
    public Awmds.BolSegment.ValueSegment.TransportSegment createAwmdsBolSegmentValueSegmentTransportSegment() {
        return new Awmds.BolSegment.ValueSegment.TransportSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.SplitSegment.Container }
     * 
     */
    public Awmds.BolSegment.SplitSegment.Container createAwmdsBolSegmentSplitSegmentContainer() {
        return new Awmds.BolSegment.SplitSegment.Container();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.GoodsSegment.SealsSegment }
     * 
     */
    public Awmds.BolSegment.GoodsSegment.SealsSegment createAwmdsBolSegmentGoodsSegmentSealsSegment() {
        return new Awmds.BolSegment.GoodsSegment.SealsSegment();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.TradersSegment.Exporter }
     * 
     */
    public Awmds.BolSegment.TradersSegment.Exporter createAwmdsBolSegmentTradersSegmentExporter() {
        return new Awmds.BolSegment.TradersSegment.Exporter();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.TradersSegment.Notify }
     * 
     */
    public Awmds.BolSegment.TradersSegment.Notify createAwmdsBolSegmentTradersSegmentNotify() {
        return new Awmds.BolSegment.TradersSegment.Notify();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.TradersSegment.Consignee }
     * 
     */
    public Awmds.BolSegment.TradersSegment.Consignee createAwmdsBolSegmentTradersSegmentConsignee() {
        return new Awmds.BolSegment.TradersSegment.Consignee();
    }

    /**
     * Create an instance of {@link Awmds.BolSegment.BolId.LineNumber }
     * 
     */
    public Awmds.BolSegment.BolId.LineNumber createAwmdsBolSegmentBolIdLineNumber() {
        return new Awmds.BolSegment.BolId.LineNumber();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.GeneralSegmentId }
     * 
     */
    public Awmds.GeneralSegment.GeneralSegmentId createAwmdsGeneralSegmentGeneralSegmentId() {
        return new Awmds.GeneralSegment.GeneralSegmentId();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.TotalsSegment }
     * 
     */
    public Awmds.GeneralSegment.TotalsSegment createAwmdsGeneralSegmentTotalsSegment() {
        return new Awmds.GeneralSegment.TotalsSegment();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.LoadUnloadPlace }
     * 
     */
    public Awmds.GeneralSegment.LoadUnloadPlace createAwmdsGeneralSegmentLoadUnloadPlace() {
        return new Awmds.GeneralSegment.LoadUnloadPlace();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.Tonnage }
     * 
     */
    public Awmds.GeneralSegment.Tonnage createAwmdsGeneralSegmentTonnage() {
        return new Awmds.GeneralSegment.Tonnage();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.AttachedDocument }
     * 
     */
    public Awmds.GeneralSegment.AttachedDocument createAwmdsGeneralSegmentAttachedDocument() {
        return new Awmds.GeneralSegment.AttachedDocument();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.TransportInformation.Carrier }
     * 
     */
    public Awmds.GeneralSegment.TransportInformation.Carrier createAwmdsGeneralSegmentTransportInformationCarrier() {
        return new Awmds.GeneralSegment.TransportInformation.Carrier();
    }

    /**
     * Create an instance of {@link Awmds.GeneralSegment.TransportInformation.ShippingAgent }
     * 
     */
    public Awmds.GeneralSegment.TransportInformation.ShippingAgent createAwmdsGeneralSegmentTransportInformationShippingAgent() {
        return new Awmds.GeneralSegment.TransportInformation.ShippingAgent();
    }

}
